# Generated by Django 6.0.2 on 2026-02-27 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_request_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
