# Generated by Django 6.0.2 on 2026-02-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran_api', '0002_alter_userprofile_last_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
